# DSO110 - Final Group Project - Lottery
Alberta "Albi" Kovatcheva and Barbra Treston



## Background
Albi and Barbra have chosen the “Mega Millions Winning Numbers” dataset because the lottery is something that is familiar and accessible to a wide range of people worldwide; it would be difficult to find someone who hasn’t dreamed of hitting the jackpot and changing their life forever. However, it is also widely accepted that the lottery is not set up to favor the player.  In the case of Mega Millions, although there is a 1 in 24 chance of winning something, the odds of choosing all 6 numbers correctly to win the jackpot is 1 in 302,575,350 - a fact that is posted openly on both the New York Lottery and Mega Millions websites.  By analyzing the winning numbers data as well as complementary datasets on lottery retailers, lottery aid to local school districts, and monies recouped from the lottery winnings of public aid recipients, Albi and Barbra hope to glean insight to make actionable suggestions on how lottery players can get the best return on their investment as well as to demonstrate for the average person whether the lottery serves any societal good or whether it may be best to abstain from playing altogether. 





## Data Wrangling

In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.mlab as mlab
import matplotlib.pyplot as plt
import math
import numpy as np
from numpy import nan
import datetime as dt
from datetime import date

### Import data.

### 1. Winning numbers May 17, 2002 to November 26, 2021

In [2]:
Winning_Numbers = pd.read_csv("Lottery_Mega_Millions_Winning_Numbers__Beginning_2002.csv")
pd.set_option("display.max_columns", None)
Winning_Numbers.head()

Draw Date Winning Numbers  Mega Ball  Multiplier
0  09/25/2020  20 36 37 48 67         16         2.0
1  09/29/2020  14 39 43 44 67         19         3.0
2  10/02/2020  09 38 47 49 68         25         2.0
3  10/06/2020  15 16 18 39 59         17         3.0
4  10/09/2020  05 11 25 27 64         13         2.0

#### Extract month, day, year, weekday, and quarter from 'Draw Date'.

In [3]:
Winning_Numbers['Draw Date']= pd.to_datetime(Winning_Numbers['Draw Date'])

In [4]:
Winning_Numbers['month'] = pd.DatetimeIndex(Winning_Numbers['Draw Date']).month

In [5]:
Winning_Numbers['day'] = pd.DatetimeIndex(Winning_Numbers['Draw Date']).day

In [6]:
Winning_Numbers['year'] = pd.DatetimeIndex(Winning_Numbers['Draw Date']).year

In [7]:
Winning_Numbers['weekday'] = pd.DatetimeIndex(Winning_Numbers['Draw Date']).dayofweek
Winning_Numbers['weekday1'] = pd.DatetimeIndex(Winning_Numbers['Draw Date']).day_name()

In [8]:
Winning_Numbers['quarter'] = pd.DatetimeIndex(Winning_Numbers['Draw Date']).quarter
Winning_Numbers.head()


Draw Date Winning Numbers  Mega Ball  Multiplier  month  day  year  \
0 2020-09-25  20 36 37 48 67         16         2.0      9   25  2020   
1 2020-09-29  14 39 43 44 67         19         3.0      9   29  2020   
2 2020-10-02  09 38 47 49 68         25         2.0     10    2  2020   
3 2020-10-06  15 16 18 39 59         17         3.0     10    6  2020   
4 2020-10-09  05 11 25 27 64         13         2.0     10    9  2020   

   weekday weekday1  quarter  
0        4   Friday        3  
1        1  Tuesday        3  
2        4   Friday        4  
3        1  Tuesday        4  
4        4   Friday        4

In [9]:
Winning_Numbers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2036 entries, 0 to 2035
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype         
---  ------           --------------  -----         
 0   Draw Date        2036 non-null   datetime64[ns]
 1   Winning Numbers  2036 non-null   object        
 2   Mega Ball        2036 non-null   int64         
 3   Multiplier       1133 non-null   float64       
 4   month            2036 non-null   int64         
 5   day              2036 non-null   int64         
 6   year             2036 non-null   int64         
 7   weekday          2036 non-null   int64         
 8   weekday1         2036 non-null   object        
 9   quarter          2036 non-null   int64         
dtypes: datetime64[ns](1), float64(1), int64(6), object(2)
memory usage: 159.2+ KB


#### Convert 'Winning Numbers' to string and then separate terms into individual columns (5).

In [10]:
Winning_Numbers["Winning Numbers"]= Winning_Numbers["Winning Numbers"].astype(str)

In [11]:
Winning_Numbers[['Ball1','Ball2',"Ball3","Ball4","Ball5"]] =  Winning_Numbers['Winning Numbers'].str.split(' ', expand=True)
Winning_Numbers.drop(columns =["Winning Numbers"], inplace = True)
Winning_Numbers.head()

Draw Date  Mega Ball  Multiplier  month  day  year  weekday weekday1  \
0 2020-09-25         16         2.0      9   25  2020        4   Friday   
1 2020-09-29         19         3.0      9   29  2020        1  Tuesday   
2 2020-10-02         25         2.0     10    2  2020        4   Friday   
3 2020-10-06         17         3.0     10    6  2020        1  Tuesday   
4 2020-10-09         13         2.0     10    9  2020        4   Friday   

   quarter Ball1 Ball2 Ball3 Ball4 Ball5  
0        3    20    36    37    48    67  
1        3    14    39    43    44    67  
2        4    09    38    47    49    68  
3        4    15    16    18    39    59  
4        4    05    11    25    27    64

In [12]:
Winning_Numbers.set_index('Draw Date')

Mega Ball  Multiplier  month  day  year  weekday weekday1  \
Draw Date                                                               
2020-09-25         16         2.0      9   25  2020        4   Friday   
2020-09-29         19         3.0      9   29  2020        1  Tuesday   
2020-10-02         25         2.0     10    2  2020        4   Friday   
2020-10-06         17         3.0     10    6  2020        1  Tuesday   
2020-10-09         13         2.0     10    9  2020        4   Friday   
...               ...         ...    ...  ...   ...      ...      ...   
2021-11-12         15         2.0     11   12  2021        4   Friday   
2021-11-16          3         3.0     11   16  2021        1  Tuesday   
2021-11-19         18         5.0     11   19  2021        4   Friday   
2021-11-23          6         3.0     11   23  2021        1  Tuesday   
2021-11-26          2         2.0     11   26  2021        4   Friday   

            quarter Ball1 Ball2 Ball3 Ball4 Ball5  
Draw Date                                          
2020-09-25        3    20    36    37    48    67  
2020-09-29        3    14    39    43    44    67  
2020-10-02        4    09    38    47    49    68  
2020-10-06        4    15    16    18    39    59  
2020-10-09        4    05    11    25    27    64  
...             ...   ...   ...   ...   ...   ...  
2021-11-12        4    30    32    42    46    48  
2021-11-16        4    06    22    44    53    65  
2021-11-19        4    05    23    52    53    59  
2021-11-23        4    07    24    54    57    58  
2021-11-26        4    07    27    37    42    59  

[2036 rows x 13 columns]

### 2. Jackpots Wins May 17, 2002 to October 22, 2021

In [13]:
Winners = pd.read_csv("jackpot winners.csv")
pd.set_option("display.max_columns", None)

Winners.head()

Date   amount  won   cash prize              location state gender
0  5/17/2002       23300000         NaN         Chatham, Ill.    IL  Mixed
1  5/24/2002       23300000         NaN         Chicago, Ill.    IL      F
2  7/16/2002       23300000         NaN  Cliffside Park, N.J.    NJ      M
3  8/27/2002       23300000         NaN   New York City, N.Y.    NY  Mixed
4   9/6/2002       23300000         NaN       Kentwood, Mich.    MI      M

In [14]:
Winners.rename(columns={'Date': 'Draw Date', ' amount  won ':'Jackpot'}, inplace=True)
Winners.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 223 entries, 0 to 222
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Draw Date   223 non-null    object 
 1   Jackpot     223 non-null    int64  
 2   cash prize  18 non-null     float64
 3   location    223 non-null    object 
 4   state       220 non-null    object 
 5   gender      223 non-null    object 
dtypes: float64(1), int64(1), object(4)
memory usage: 10.6+ KB


In [15]:
Winners['Draw Date']= pd.to_datetime(Winners['Draw Date'])

In [16]:
Wins = pd.DataFrame(Winners.groupby('Draw Date')['Jackpot'].sum())
Wins

Jackpot
Draw Date             
2002-05-17    23300000
2002-05-24    23300000
2002-07-16    23300000
2002-08-27    23300000
2002-09-06    23300000
...                ...
2021-02-23  1050000000
2021-05-21   516000000
2021-09-07    55000000
2021-09-21   431000000
2021-10-22   108000000

[198 rows x 1 columns]

### 3. Non-Jackpot Wins October 16, 2012 to November 26, 2021


In [17]:
SmallWinners = pd.read_csv("nonjackpot winners.csv")
pd.set_option("display.max_columns", None)
SmallWinners.head()

Draw Date    Prize Gender              City State
0  11/26/2021  2000000      M  Washtenaw County    MI
1   9/21/2021    30000      M         Baltimore    MD
2   8/31/2021  3000000      M        New Berlin    WI
3   8/20/2021  1000000      F      Newport News    VA
4   7/27/2021  3000000    Unk      Grand Strand    SC

In [18]:
SmallWinners['Draw Date']= pd.to_datetime(SmallWinners['Draw Date'])
SmallWins = pd.DataFrame(SmallWinners.groupby('Draw Date')['Prize'].sum())
SmallWins

Prize
Draw Date           
2012-10-16   3005000
2012-11-27  50000000
2013-10-25    479070
2013-11-01   1000000
2013-11-05    410115
...              ...
2021-07-27   3000000
2021-08-20   1000000
2021-08-31   3000000
2021-09-21     30000
2021-11-26   2000000

[213 rows x 1 columns]

### Merging the Datasets

In [19]:
Prizes = Wins.merge(SmallWins, how='outer', on='Draw Date')
Prizes.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 387 entries, 2002-05-17 to 2021-11-26
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   Jackpot  198 non-null    float64
 1   Prize    213 non-null    float64
dtypes: float64(2)
memory usage: 9.1 KB


In [20]:
Winning_Numbers = Winning_Numbers.merge(Prizes, how='left', on='Draw Date')

In [21]:
Winning_Numbers.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2036 entries, 0 to 2035
Data columns (total 16 columns):
 #   Column      Non-Null Count  Dtype         
---  ------      --------------  -----         
 0   Draw Date   2036 non-null   datetime64[ns]
 1   Mega Ball   2036 non-null   int64         
 2   Multiplier  1133 non-null   float64       
 3   month       2036 non-null   int64         
 4   day         2036 non-null   int64         
 5   year        2036 non-null   int64         
 6   weekday     2036 non-null   int64         
 7   weekday1    2036 non-null   object        
 8   quarter     2036 non-null   int64         
 9   Ball1       2036 non-null   object        
 10  Ball2       2036 non-null   object        
 11  Ball3       2036 non-null   object        
 12  Ball4       2036 non-null   object        
 13  Ball5       2036 non-null   object        
 14  Jackpot     198 non-null    float64       
 15  Prize       213 non-null    float64       
dtypes: datetime64[ns](1), fl

In [22]:
Winning_Numbers

Draw Date  Mega Ball  Multiplier  month  day  year  weekday weekday1  \
0    2020-09-25         16         2.0      9   25  2020        4   Friday   
1    2020-09-29         19         3.0      9   29  2020        1  Tuesday   
2    2020-10-02         25         2.0     10    2  2020        4   Friday   
3    2020-10-06         17         3.0     10    6  2020        1  Tuesday   
4    2020-10-09         13         2.0     10    9  2020        4   Friday   
...         ...        ...         ...    ...  ...   ...      ...      ...   
2031 2021-11-12         15         2.0     11   12  2021        4   Friday   
2032 2021-11-16          3         3.0     11   16  2021        1  Tuesday   
2033 2021-11-19         18         5.0     11   19  2021        4   Friday   
2034 2021-11-23          6         3.0     11   23  2021        1  Tuesday   
2035 2021-11-26          2         2.0     11   26  2021        4   Friday   

      quarter Ball1 Ball2 Ball3 Ball4 Ball5  Jackpot      Prize  
0           3    20    36    37    48    67      NaN        NaN  
1           3    14    39    43    44    67      NaN        NaN  
2           4    09    38    47    49    68      NaN        NaN  
3           4    15    16    18    39    59      NaN        NaN  
4           4    05    11    25    27    64      NaN  2000000.0  
...       ...   ...   ...   ...   ...   ...      ...        ...  
2031        4    30    32    42    46    48      NaN        NaN  
2032        4    06    22    44    53    65      NaN        NaN  
2033        4    05    23    52    53    59      NaN        NaN  
2034        4    07    24    54    57    58      NaN        NaN  
2035        4    07    27    37    42    59      NaN  2000000.0  

[2036 rows x 16 columns]

In [23]:
Winning_Numbers.set_index('Draw Date')

Mega Ball  Multiplier  month  day  year  weekday weekday1  \
Draw Date                                                               
2020-09-25         16         2.0      9   25  2020        4   Friday   
2020-09-29         19         3.0      9   29  2020        1  Tuesday   
2020-10-02         25         2.0     10    2  2020        4   Friday   
2020-10-06         17         3.0     10    6  2020        1  Tuesday   
2020-10-09         13         2.0     10    9  2020        4   Friday   
...               ...         ...    ...  ...   ...      ...      ...   
2021-11-12         15         2.0     11   12  2021        4   Friday   
2021-11-16          3         3.0     11   16  2021        1  Tuesday   
2021-11-19         18         5.0     11   19  2021        4   Friday   
2021-11-23          6         3.0     11   23  2021        1  Tuesday   
2021-11-26          2         2.0     11   26  2021        4   Friday   

            quarter Ball1 Ball2 Ball3 Ball4 Ball5  Jackpot      Prize  
Draw Date                                                              
2020-09-25        3    20    36    37    48    67      NaN        NaN  
2020-09-29        3    14    39    43    44    67      NaN        NaN  
2020-10-02        4    09    38    47    49    68      NaN        NaN  
2020-10-06        4    15    16    18    39    59      NaN        NaN  
2020-10-09        4    05    11    25    27    64      NaN  2000000.0  
...             ...   ...   ...   ...   ...   ...      ...        ...  
2021-11-12        4    30    32    42    46    48      NaN        NaN  
2021-11-16        4    06    22    44    53    65      NaN        NaN  
2021-11-19        4    05    23    52    53    59      NaN        NaN  
2021-11-23        4    07    24    54    57    58      NaN        NaN  
2021-11-26        4    07    27    37    42    59      NaN  2000000.0  

[2036 rows x 15 columns]

In [24]:
len(Winning_Numbers)

2036

In [25]:
Winning_Numbers['Index'] = Winning_Numbers.reset_index().index
Winning_Numbers

Draw Date  Mega Ball  Multiplier  month  day  year  weekday weekday1  \
0    2020-09-25         16         2.0      9   25  2020        4   Friday   
1    2020-09-29         19         3.0      9   29  2020        1  Tuesday   
2    2020-10-02         25         2.0     10    2  2020        4   Friday   
3    2020-10-06         17         3.0     10    6  2020        1  Tuesday   
4    2020-10-09         13         2.0     10    9  2020        4   Friday   
...         ...        ...         ...    ...  ...   ...      ...      ...   
2031 2021-11-12         15         2.0     11   12  2021        4   Friday   
2032 2021-11-16          3         3.0     11   16  2021        1  Tuesday   
2033 2021-11-19         18         5.0     11   19  2021        4   Friday   
2034 2021-11-23          6         3.0     11   23  2021        1  Tuesday   
2035 2021-11-26          2         2.0     11   26  2021        4   Friday   

      quarter Ball1 Ball2 Ball3 Ball4 Ball5  Jackpot      Prize  Index  
0           3    20    36    37    48    67      NaN        NaN      0  
1           3    14    39    43    44    67      NaN        NaN      1  
2           4    09    38    47    49    68      NaN        NaN      2  
3           4    15    16    18    39    59      NaN        NaN      3  
4           4    05    11    25    27    64      NaN  2000000.0      4  
...       ...   ...   ...   ...   ...   ...      ...        ...    ...  
2031        4    30    32    42    46    48      NaN        NaN   2031  
2032        4    06    22    44    53    65      NaN        NaN   2032  
2033        4    05    23    52    53    59      NaN        NaN   2033  
2034        4    07    24    54    57    58      NaN        NaN   2034  
2035        4    07    27    37    42    59      NaN  2000000.0   2035  

[2036 rows x 17 columns]

### Export data to excel file.

In [26]:
Winning_Numbers.to_csv('Lottery_Mega_Millions_Winning_Numbers__Beginning_2002_Wrangled.csv')

## Data Exploration

## Machine Learning

## Decision Tree. 
Based on Balls 1-5, to what extent can I predict the megaball?

In [27]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

### Import Data.

In [28]:
Winning_Numbers1 = pd.read_csv("Lottery_Mega_Millions_Winning_Numbers__Beginning_2002_Wrangled.csv")
Winning_Numbers1.head()
# Titanic = sns.load_dataset('titanic')

Unnamed: 0   Draw Date  Mega Ball  Multiplier  month  day  year  weekday  \
0           0  2020-09-25         16         2.0      9   25  2020        4   
1           1  2020-09-29         19         3.0      9   29  2020        1   
2           2  2020-10-02         25         2.0     10    2  2020        4   
3           3  2020-10-06         17         3.0     10    6  2020        1   
4           4  2020-10-09         13         2.0     10    9  2020        4   

  weekday1  quarter  Ball1  Ball2  Ball3  Ball4  Ball5  Jackpot      Prize  \
0   Friday        3     20     36     37     48     67      NaN        NaN   
1  Tuesday        3     14     39     43     44     67      NaN        NaN   
2   Friday        4      9     38     47     49     68      NaN        NaN   
3  Tuesday        4     15     16     18     39     59      NaN        NaN   
4   Friday        4      5     11     25     27     64      NaN  2000000.0   

   Index  
0      0  
1      1  
2      2  
3      3  
4      4

### See Data Types.

In [29]:
Winning_Numbers1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2036 entries, 0 to 2035
Data columns (total 18 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Unnamed: 0  2036 non-null   int64  
 1   Draw Date   2036 non-null   object 
 2   Mega Ball   2036 non-null   int64  
 3   Multiplier  1133 non-null   float64
 4   month       2036 non-null   int64  
 5   day         2036 non-null   int64  
 6   year        2036 non-null   int64  
 7   weekday     2036 non-null   int64  
 8   weekday1    2036 non-null   object 
 9   quarter     2036 non-null   int64  
 10  Ball1       2036 non-null   int64  
 11  Ball2       2036 non-null   int64  
 12  Ball3       2036 non-null   int64  
 13  Ball4       2036 non-null   int64  
 14  Ball5       2036 non-null   int64  
 15  Jackpot     198 non-null    float64
 16  Prize       213 non-null    float64
 17  Index       2036 non-null   int64  
dtypes: float64(3), int64(13), object(2)
memory usage: 286.4+ KB


### Rename 'Mega Ball' column.

In [30]:
Winning_Numbers1 = Winning_Numbers1.rename(columns={'Mega Ball': 'Mega_Ball'})
# df = df.rename(columns={'oldName1': 'newName1', 'oldName2': 'newName2'})

### See Data Types Again.

In [31]:
Winning_Numbers1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2036 entries, 0 to 2035
Data columns (total 18 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Unnamed: 0  2036 non-null   int64  
 1   Draw Date   2036 non-null   object 
 2   Mega_Ball   2036 non-null   int64  
 3   Multiplier  1133 non-null   float64
 4   month       2036 non-null   int64  
 5   day         2036 non-null   int64  
 6   year        2036 non-null   int64  
 7   weekday     2036 non-null   int64  
 8   weekday1    2036 non-null   object 
 9   quarter     2036 non-null   int64  
 10  Ball1       2036 non-null   int64  
 11  Ball2       2036 non-null   int64  
 12  Ball3       2036 non-null   int64  
 13  Ball4       2036 non-null   int64  
 14  Ball5       2036 non-null   int64  
 15  Jackpot     198 non-null    float64
 16  Prize       213 non-null    float64
 17  Index       2036 non-null   int64  
dtypes: float64(3), int64(13), object(2)
memory usage: 286.4+ KB


### Set data types.

In [32]:
# Winning_Numbers1.Ball1 = Winning_Numbers1.Ball1.astype(int)
# Winning_Numbers1.Ball2 = Winning_Numbers1.Ball2.astype(int)
# Winning_Numbers1.Ball3 = Winning_Numbers1.Ball3.astype(int)
# Winning_Numbers1.Ball4 = Winning_Numbers1.Ball4.astype(int)
# Winning_Numbers1.Ball5 = Winning_Numbers1.Ball5.astype(int)
# Winning_Numbers1.Mega_Ball = Winning_Numbers1.Mega_Ball.astype(int)
# Titanic.fare = Titanic.fare.astype(int)

### See Data Types Again.

In [33]:
Winning_Numbers1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2036 entries, 0 to 2035
Data columns (total 18 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Unnamed: 0  2036 non-null   int64  
 1   Draw Date   2036 non-null   object 
 2   Mega_Ball   2036 non-null   int64  
 3   Multiplier  1133 non-null   float64
 4   month       2036 non-null   int64  
 5   day         2036 non-null   int64  
 6   year        2036 non-null   int64  
 7   weekday     2036 non-null   int64  
 8   weekday1    2036 non-null   object 
 9   quarter     2036 non-null   int64  
 10  Ball1       2036 non-null   int64  
 11  Ball2       2036 non-null   int64  
 12  Ball3       2036 non-null   int64  
 13  Ball4       2036 non-null   int64  
 14  Ball5       2036 non-null   int64  
 15  Jackpot     198 non-null    float64
 16  Prize       213 non-null    float64
 17  Index       2036 non-null   int64  
dtypes: float64(3), int64(13), object(2)
memory usage: 286.4+ KB


### Specify Predictor and Response Variables.

In [34]:
x = Winning_Numbers1.drop(['Draw Date', 'Multiplier', 'month', 'day', 'year', 'weekday', 'weekday1', 'quarter', 'Jackpot', 'Prize'], axis=1)
y = Winning_Numbers1['Mega_Ball']
# x = Titanic.drop('survived', axis=1)
# y = Titanic['survived']

### Train-Test-Split.

In [35]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.50)

### Implement Decision Tree.

In [36]:
decisionTree = DecisionTreeClassifier(random_state=76)
decisionTree.fit(x_train, y_train)

DecisionTreeClassifier(random_state=76)

In [37]:
treePredictions = decisionTree.predict(x_test)
treePredictions

array([25, 19,  5, ..., 19, 27, 25], dtype=int64)

In [38]:
treePredictions = decisionTree.predict(x_test)
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(confusion_matrix(y_test, treePredictions))
print(classification_report(y_test, treePredictions))
# 1. Support is the number of actual occurrences of the class in the specified dataset.
# 2. A Confusion matrix is an N x N matrix used for evaluating the performance of a classification model, 
# where N is the number of target classes. The matrix compares the actual target values with those predicted 
# by the machine learning model.

[[38  0  0 ...  0  0  0]
 [ 0 30  0 ...  0  0  0]
 [ 0  0 35 ...  0  0  0]
 ...
 [ 0  0  0 ...  4  0  0]
 [ 0  0  0 ...  0  2  0]
 [ 0  0  0 ...  0  0  6]]
              precision    recall  f1-score   support

           1       1.00      1.00      1.00        38
           2       1.00      1.00      1.00        30
           3       1.00      1.00      1.00        35
           4       1.00      1.00      1.00        30
           5       1.00      1.00      1.00        23
           6       1.00      1.00      1.00        35
           7       1.00      1.00      1.00        41
           8       1.00      1.00      1.00        31
           9       1.00      1.00      1.00        43
          10       1.00      1.00      1.00        37
          11       1.00      1.00      1.00        42
          12       1.00      1.00      1.00        31
          13       1.00      1.00      1.00        33
          14       1.00      1.00      1.00        35
          15       1.00      1.00

In [39]:
# Redundant
print(confusion_matrix(y_test, treePredictions))

[[38  0  0 ...  0  0  0]
 [ 0 30  0 ...  0  0  0]
 [ 0  0 35 ...  0  0  0]
 ...
 [ 0  0  0 ...  4  0  0]
 [ 0  0  0 ...  0  2  0]
 [ 0  0  0 ...  0  0  6]]


In [40]:
# Redundant
print(classification_report(y_test, treePredictions))

              precision    recall  f1-score   support

           1       1.00      1.00      1.00        38
           2       1.00      1.00      1.00        30
           3       1.00      1.00      1.00        35
           4       1.00      1.00      1.00        30
           5       1.00      1.00      1.00        23
           6       1.00      1.00      1.00        35
           7       1.00      1.00      1.00        41
           8       1.00      1.00      1.00        31
           9       1.00      1.00      1.00        43
          10       1.00      1.00      1.00        37
          11       1.00      1.00      1.00        42
          12       1.00      1.00      1.00        31
          13       1.00      1.00      1.00        33
          14       1.00      1.00      1.00        35
          15       1.00      1.00      1.00        42
          16       1.00      1.00      1.00        19
          17       1.00      1.00      1.00        16
          18       1.00    

In [41]:
# from sklearn.linear_model import LinearRegression
# from sklearn.model_selection import train_test_split
# %matplotlib inline
# from sklearn import metrics


In [42]:
# Winning_Numbers['Ball1'] =Winning_Numbers['Ball1'].astype('category')
# Winning_Numbers['Ball2'] =Winning_Numbers['Ball2'].astype('category')
# Winning_Numbers['Ball3'] =Winning_Numbers['Ball3'].astype('category')
# Winning_Numbers['Ball4'] =Winning_Numbers['Ball4'].astype('category')
# Winning_Numbers['Ball5'] =Winning_Numbers['Ball5'].astype('category')
# Winning_Numbers['Mega Ball'] =Winning_Numbers['Mega Ball'].astype('category')

# cat_feat = ['Mega Ball','Multiplier']
# for feat in cat_feat:
#     Winning_Numbers[feat] = Winning_Numbers[feat].astype('category')

In [43]:
# x = realestate[['X2 house age', 'X3 distance to the nearest MRT station', 'X4 number of convenience stores', 'X5 latitude', 'X6 longitude']]

In [44]:
# y = realestate['Y house price of unit area']


In [45]:
# Winning_Numbers1 = LinearRegression()
# Winning_Numbers1.fit(x_train, y_train)

# lm = LinearRegression()
# lm.fit(x_train, y_train)

In [46]:
# LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
#          normalize=False)

In [47]:
# X = Winning_Numbers.drop(['Mega Ball'],axis=1)
# y = Winning_Numbers['Mega Ball']

In [48]:
#from sklearn.linear_model import LogisticRegression
#from sklearn.metrics import classification_report, confusion_matrix
#models = []
#models.append(("LR",LogisticRegression(solver='liblinear')))
#print(models)

In [49]:
#import statsmodels.formula.api as smf
#model_fit3 = smf.logit(formula='MegaBall ~C(Ball1)+C(Ball2)', data=winning_numbers).fit()