# DSO110 - Final Group Project - Lottery
Alberta "Albi" Kovatcheva and Barbra Treston



## Background
Albi and Barbra have chosen the “Mega Millions Winning Numbers” dataset because the lottery is something that is familiar and accessible to a wide range of people worldwide; it would be difficult to find someone who hasn’t dreamed of hitting the jackpot and changing their life forever. However, it is also widely accepted that the lottery is not set up to favor the player.  In the case of Mega Millions, although there is a 1 in 24 chance of winning something, the odds of choosing all 6 numbers correctly to win the jackpot is 1 in 302,575,350 - a fact that is posted openly on both the New York Lottery and Mega Millions websites.  By analyzing the winning numbers data as well as complementary datasets on lottery retailers, lottery aid to local school districts, and monies recouped from the lottery winnings of public aid recipients, Albi and Barbra hope to glean insight to make actionable suggestions on how lottery players can get the best return on their investment as well as to demonstrate for the average person whether the lottery serves any societal good or whether it may be best to abstain from playing altogether. 





## Data Wrangling

In [214]:
import pandas as pd
import seaborn as sns
import matplotlib.mlab as mlab
import matplotlib.pyplot as plt
import math
import numpy as np
from numpy import nan
import datetime as dt
from datetime import date

### Import data.

### 1. Winning numbers May 17, 2002 to November 26, 2021

In [215]:
Winning_Numbers = pd.read_csv("Lottery_Mega_Millions_Winning_Numbers__Beginning_2002.csv")
pd.set_option("display.max_columns", None)
Winning_Numbers.head()

Draw Date Winning Numbers  Mega Ball  Multiplier
0  09/25/2020  20 36 37 48 67         16         2.0
1  09/29/2020  14 39 43 44 67         19         3.0
2  10/02/2020  09 38 47 49 68         25         2.0
3  10/06/2020  15 16 18 39 59         17         3.0
4  10/09/2020  05 11 25 27 64         13         2.0

#### Extract month, day, year, weekday, and quarter from 'Draw Date'.

In [216]:
Winning_Numbers['Draw Date']= pd.to_datetime(Winning_Numbers['Draw Date'])
Winning_Numbers['month'] = pd.DatetimeIndex(Winning_Numbers['Draw Date']).month
Winning_Numbers['day'] = pd.DatetimeIndex(Winning_Numbers['Draw Date']).day
Winning_Numbers['year'] = pd.DatetimeIndex(Winning_Numbers['Draw Date']).year
Winning_Numbers['weekday'] = pd.DatetimeIndex(Winning_Numbers['Draw Date']).dayofweek
Winning_Numbers['weekday1'] = pd.DatetimeIndex(Winning_Numbers['Draw Date']).day_name()
Winning_Numbers['quarter'] = pd.DatetimeIndex(Winning_Numbers['Draw Date']).quarter
Winning_Numbers.head()


Draw Date Winning Numbers  Mega Ball  Multiplier  month  day  year  \
0 2020-09-25  20 36 37 48 67         16         2.0      9   25  2020   
1 2020-09-29  14 39 43 44 67         19         3.0      9   29  2020   
2 2020-10-02  09 38 47 49 68         25         2.0     10    2  2020   
3 2020-10-06  15 16 18 39 59         17         3.0     10    6  2020   
4 2020-10-09  05 11 25 27 64         13         2.0     10    9  2020   

   weekday weekday1  quarter  
0        4   Friday        3  
1        1  Tuesday        3  
2        4   Friday        4  
3        1  Tuesday        4  
4        4   Friday        4

In [217]:
Winning_Numbers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2036 entries, 0 to 2035
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype         
---  ------           --------------  -----         
 0   Draw Date        2036 non-null   datetime64[ns]
 1   Winning Numbers  2036 non-null   object        
 2   Mega Ball        2036 non-null   int64         
 3   Multiplier       1133 non-null   float64       
 4   month            2036 non-null   int64         
 5   day              2036 non-null   int64         
 6   year             2036 non-null   int64         
 7   weekday          2036 non-null   int64         
 8   weekday1         2036 non-null   object        
 9   quarter          2036 non-null   int64         
dtypes: datetime64[ns](1), float64(1), int64(6), object(2)
memory usage: 159.2+ KB


#### Convert 'Winning Numbers' to string and then separate terms into individual columns (5).

In [218]:
Winning_Numbers["Winning Numbers"]= Winning_Numbers["Winning Numbers"].astype(str)
Winning_Numbers[['Ball1','Ball2',"Ball3","Ball4","Ball5"]] =  Winning_Numbers['Winning Numbers'].str.split(' ', expand=True)
Winning_Numbers.drop(columns =["Winning Numbers"], inplace = True)
Winning_Numbers.head()

Draw Date  Mega Ball  Multiplier  month  day  year  weekday weekday1  \
0 2020-09-25         16         2.0      9   25  2020        4   Friday   
1 2020-09-29         19         3.0      9   29  2020        1  Tuesday   
2 2020-10-02         25         2.0     10    2  2020        4   Friday   
3 2020-10-06         17         3.0     10    6  2020        1  Tuesday   
4 2020-10-09         13         2.0     10    9  2020        4   Friday   

   quarter Ball1 Ball2 Ball3 Ball4 Ball5  
0        3    20    36    37    48    67  
1        3    14    39    43    44    67  
2        4    09    38    47    49    68  
3        4    15    16    18    39    59  
4        4    05    11    25    27    64

### 2. Jackpots Wins May 17, 2002 to October 22, 2021

In [219]:
Winners = pd.read_csv("jackpot winners.csv")
pd.set_option("display.max_columns", None)
Winners.head()

Date   amount  won   cash prize              location state gender
0  5/17/2002       23300000         NaN         Chatham, Ill.    IL  Mixed
1  5/24/2002       23300000         NaN         Chicago, Ill.    IL      F
2  7/16/2002       23300000         NaN  Cliffside Park, N.J.    NJ      M
3  8/27/2002       23300000         NaN   New York City, N.Y.    NY  Mixed
4   9/6/2002       23300000         NaN       Kentwood, Mich.    MI      M

In [220]:
Winners.rename(columns={'Date': 'Draw Date', ' amount  won ':'JackpotAmount', 'location':'Location', 'state':'State', 'gender':'Gender'}, inplace=True)
Winners.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 223 entries, 0 to 222
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Draw Date      223 non-null    object 
 1   JackpotAmount  223 non-null    int64  
 2   cash prize     18 non-null     float64
 3   Location       223 non-null    object 
 4   State          220 non-null    object 
 5   Gender         223 non-null    object 
dtypes: float64(1), int64(1), object(4)
memory usage: 10.6+ KB


In [221]:
Winners['Draw Date']= pd.to_datetime(Winners['Draw Date'])

In [222]:
Winners['Win'] = 'Y'
Winners['Jackpot'] = 'Y'

In [223]:
Wins = pd.DataFrame(Winners.groupby('Draw Date')['JackpotAmount'].sum())
Wins

JackpotAmount
Draw Date                
2002-05-17       23300000
2002-05-24       23300000
2002-07-16       23300000
2002-08-27       23300000
2002-09-06       23300000
...                   ...
2021-02-23     1050000000
2021-05-21      516000000
2021-09-07       55000000
2021-09-21      431000000
2021-10-22      108000000

[198 rows x 1 columns]

### 3. Non-Jackpot Wins October 16, 2012 to November 26, 2021


In [224]:
SmallWinners = pd.read_csv("nonjackpot winners.csv")
pd.set_option("display.max_columns", None)
SmallWinners.head()

Draw Date    Prize Gender              City State
0  11/26/2021  2000000      M  Washtenaw County    MI
1   9/21/2021    30000      M         Baltimore    MD
2   8/31/2021  3000000      M        New Berlin    WI
3   8/20/2021  1000000      F      Newport News    VA
4   7/27/2021  3000000    Unk      Grand Strand    SC

In [225]:
SmallWinners.rename(columns={'Date': 'Draw Date', 'Prize':'NonJackpotAmount', 'City':'Location'}, inplace=True)
SmallWinners['Win'] = 'Y'
SmallWinners['Jackpot'] = 'N'
SmallWinners.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 274 entries, 0 to 273
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype 
---  ------            --------------  ----- 
 0   Draw Date         274 non-null    object
 1   NonJackpotAmount  274 non-null    int64 
 2   Gender            274 non-null    object
 3   Location          274 non-null    object
 4   State             274 non-null    object
 5   Win               274 non-null    object
 6   Jackpot           274 non-null    object
dtypes: int64(1), object(6)
memory usage: 15.1+ KB


In [226]:
SmallWinners['Draw Date']= pd.to_datetime(SmallWinners['Draw Date'])
SmallWins = pd.DataFrame(SmallWinners.groupby('Draw Date')['NonJackpotAmount'].sum())
SmallWins

NonJackpotAmount
Draw Date                   
2012-10-16           3005000
2012-11-27          50000000
2013-10-25            479070
2013-11-01           1000000
2013-11-05            410115
...                      ...
2021-07-27           3000000
2021-08-20           1000000
2021-08-31           3000000
2021-09-21             30000
2021-11-26           2000000

[213 rows x 1 columns]

### Merging the Datasets

#### A. Winning Numbers plus Total Jackpot and Non-Jackpot Winnings

In [227]:
Prizes = Wins.merge(SmallWins, how='outer', on='Draw Date')
Prizes.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 387 entries, 2002-05-17 to 2021-11-26
Data columns (total 2 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   JackpotAmount     198 non-null    float64
 1   NonJackpotAmount  213 non-null    float64
dtypes: float64(2)
memory usage: 9.1 KB


In [228]:
Winning_Numbers = Winning_Numbers.merge(Prizes, how='left', on='Draw Date')

In [229]:
Winning_Numbers.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2036 entries, 0 to 2035
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype         
---  ------            --------------  -----         
 0   Draw Date         2036 non-null   datetime64[ns]
 1   Mega Ball         2036 non-null   int64         
 2   Multiplier        1133 non-null   float64       
 3   month             2036 non-null   int64         
 4   day               2036 non-null   int64         
 5   year              2036 non-null   int64         
 6   weekday           2036 non-null   int64         
 7   weekday1          2036 non-null   object        
 8   quarter           2036 non-null   int64         
 9   Ball1             2036 non-null   object        
 10  Ball2             2036 non-null   object        
 11  Ball3             2036 non-null   object        
 12  Ball4             2036 non-null   object        
 13  Ball5             2036 non-null   object        
 14  JackpotAmount     198 no

In [230]:
Winning_Numbers

Draw Date  Mega Ball  Multiplier  month  day  year  weekday weekday1  \
0    2020-09-25         16         2.0      9   25  2020        4   Friday   
1    2020-09-29         19         3.0      9   29  2020        1  Tuesday   
2    2020-10-02         25         2.0     10    2  2020        4   Friday   
3    2020-10-06         17         3.0     10    6  2020        1  Tuesday   
4    2020-10-09         13         2.0     10    9  2020        4   Friday   
...         ...        ...         ...    ...  ...   ...      ...      ...   
2031 2021-11-12         15         2.0     11   12  2021        4   Friday   
2032 2021-11-16          3         3.0     11   16  2021        1  Tuesday   
2033 2021-11-19         18         5.0     11   19  2021        4   Friday   
2034 2021-11-23          6         3.0     11   23  2021        1  Tuesday   
2035 2021-11-26          2         2.0     11   26  2021        4   Friday   

      quarter Ball1 Ball2 Ball3 Ball4 Ball5  JackpotAmount  NonJackpotAmount  
0           3    20    36    37    48    67            NaN               NaN  
1           3    14    39    43    44    67            NaN               NaN  
2           4    09    38    47    49    68            NaN               NaN  
3           4    15    16    18    39    59            NaN               NaN  
4           4    05    11    25    27    64            NaN         2000000.0  
...       ...   ...   ...   ...   ...   ...            ...               ...  
2031        4    30    32    42    46    48            NaN               NaN  
2032        4    06    22    44    53    65            NaN               NaN  
2033        4    05    23    52    53    59            NaN               NaN  
2034        4    07    24    54    57    58            NaN               NaN  
2035        4    07    27    37    42    59            NaN         2000000.0  

[2036 rows x 16 columns]

##### Export data to excel file.

In [231]:
Winning_Numbers.to_csv('Lottery_Mega_Millions_Winning_Numbers__Beginning_2002_Wrangled.csv')  

#### B. Jackpot & Non-Jackpot Winners

In [232]:
AllWinners = pd.merge(Winners, SmallWinners, on=['Draw Date', 'Location', 'State', 'Gender', 'Win', 'Jackpot'], how='outer')
AllWinners.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 497 entries, 0 to 496
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype         
---  ------            --------------  -----         
 0   Draw Date         497 non-null    datetime64[ns]
 1   JackpotAmount     223 non-null    float64       
 2   cash prize        18 non-null     float64       
 3   Location          497 non-null    object        
 4   State             494 non-null    object        
 5   Gender            497 non-null    object        
 6   Win               497 non-null    object        
 7   Jackpot           497 non-null    object        
 8   NonJackpotAmount  274 non-null    float64       
dtypes: datetime64[ns](1), float64(3), object(5)
memory usage: 38.8+ KB


##### Export data to excel file.

In [233]:
AllWinners.to_csv('AllWinners.csv')  

## Data Exploration

## Machine Learning

## Decision Tree. 
Based on Balls 1-5, to what extent can I predict the megaball?

In [234]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

### Import Data.

### See Data Types.

In [235]:
Winning_Numbers.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2036 entries, 0 to 2035
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype         
---  ------            --------------  -----         
 0   Draw Date         2036 non-null   datetime64[ns]
 1   Mega Ball         2036 non-null   int64         
 2   Multiplier        1133 non-null   float64       
 3   month             2036 non-null   int64         
 4   day               2036 non-null   int64         
 5   year              2036 non-null   int64         
 6   weekday           2036 non-null   int64         
 7   weekday1          2036 non-null   object        
 8   quarter           2036 non-null   int64         
 9   Ball1             2036 non-null   object        
 10  Ball2             2036 non-null   object        
 11  Ball3             2036 non-null   object        
 12  Ball4             2036 non-null   object        
 13  Ball5             2036 non-null   object        
 14  JackpotAmount     198 no

### Rename 'Mega Ball' column.

In [236]:
Winning_Numbers = Winning_Numbers.rename(columns={'Mega Ball': 'Mega_Ball'})
# df = df.rename(columns={'oldName1': 'newName1', 'oldName2': 'newName2'})

### See Data Types Again.

In [237]:
Winning_Numbers.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2036 entries, 0 to 2035
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype         
---  ------            --------------  -----         
 0   Draw Date         2036 non-null   datetime64[ns]
 1   Mega_Ball         2036 non-null   int64         
 2   Multiplier        1133 non-null   float64       
 3   month             2036 non-null   int64         
 4   day               2036 non-null   int64         
 5   year              2036 non-null   int64         
 6   weekday           2036 non-null   int64         
 7   weekday1          2036 non-null   object        
 8   quarter           2036 non-null   int64         
 9   Ball1             2036 non-null   object        
 10  Ball2             2036 non-null   object        
 11  Ball3             2036 non-null   object        
 12  Ball4             2036 non-null   object        
 13  Ball5             2036 non-null   object        
 14  JackpotAmount     198 no

### Set data types.

In [238]:
Winning_Numbers.Ball1 = Winning_Numbers.Ball1.astype(int)
Winning_Numbers.Ball2 = Winning_Numbers.Ball2.astype(int)
Winning_Numbers.Ball3 = Winning_Numbers.Ball3.astype(int)
Winning_Numbers.Ball4 = Winning_Numbers.Ball4.astype(int)
Winning_Numbers.Ball5 = Winning_Numbers.Ball5.astype(int)
Winning_Numbers.Mega_Ball = Winning_Numbers.Mega_Ball.astype(int)
# Titanic.fare = Titanic.fare.astype(int)

### See Data Types Again.

In [239]:
Winning_Numbers.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2036 entries, 0 to 2035
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype         
---  ------            --------------  -----         
 0   Draw Date         2036 non-null   datetime64[ns]
 1   Mega_Ball         2036 non-null   int32         
 2   Multiplier        1133 non-null   float64       
 3   month             2036 non-null   int64         
 4   day               2036 non-null   int64         
 5   year              2036 non-null   int64         
 6   weekday           2036 non-null   int64         
 7   weekday1          2036 non-null   object        
 8   quarter           2036 non-null   int64         
 9   Ball1             2036 non-null   int32         
 10  Ball2             2036 non-null   int32         
 11  Ball3             2036 non-null   int32         
 12  Ball4             2036 non-null   int32         
 13  Ball5             2036 non-null   int32         
 14  JackpotAmount     198 no

### Specify Predictor and Response Variables.

In [240]:
x = Winning_Numbers.drop(['Draw Date', 'Multiplier', 'month', 'day', 'year', 'weekday', 'weekday1', 'quarter', 'JackpotAmount', 'NonJackpotAmount'], axis=1)
y = Winning_Numbers['Mega_Ball']
# x = Titanic.drop('survived', axis=1)
# y = Titanic['survived']

### Train-Test-Split.

In [241]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.50)

### Implement Decision Tree.

In [242]:
decisionTree = DecisionTreeClassifier(random_state=76)
decisionTree.fit(x_train, y_train)

DecisionTreeClassifier(random_state=76)

In [243]:
treePredictions = decisionTree.predict(x_test)
treePredictions

array([ 9, 38, 49, ...,  9, 19, 22])

In [244]:
treePredictions = decisionTree.predict(x_test)
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(confusion_matrix(y_test, treePredictions))
print(classification_report(y_test, treePredictions))
# 1. Support is the number of actual occurrences of the class in the specified dataset.
# 2. A Confusion matrix is an N x N matrix used for evaluating the performance of a classification model, 
# where N is the number of target classes. The matrix compares the actual target values with those predicted 
# by the machine learning model.

[[35  0  0 ...  0  0  0]
 [ 0 34  0 ...  0  0  0]
 [ 0  0 38 ...  0  0  0]
 ...
 [ 0  0  0 ...  1  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  4]]
              precision    recall  f1-score   support

           1       1.00      1.00      1.00        35
           2       1.00      1.00      1.00        34
           3       1.00      1.00      1.00        38
           4       1.00      1.00      1.00        37
           5       1.00      1.00      1.00        28
           6       1.00      1.00      1.00        38
           7       1.00      1.00      1.00        35
           8       1.00      1.00      1.00        33
           9       1.00      1.00      1.00        35
          10       1.00      1.00      1.00        37
          11       1.00      1.00      1.00        34
          12       1.00      1.00      1.00        34
          13       1.00      1.00      1.00        38
          14       1.00      1.00      1.00        30
          15       1.00      1.00

C:\Users\betre\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\betre\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\betre\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [245]:
# Redundant
print(confusion_matrix(y_test, treePredictions))

[[35  0  0 ...  0  0  0]
 [ 0 34  0 ...  0  0  0]
 [ 0  0 38 ...  0  0  0]
 ...
 [ 0  0  0 ...  1  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  4]]


In [246]:
# Redundant
print(classification_report(y_test, treePredictions))

              precision    recall  f1-score   support

           1       1.00      1.00      1.00        35
           2       1.00      1.00      1.00        34
           3       1.00      1.00      1.00        38
           4       1.00      1.00      1.00        37
           5       1.00      1.00      1.00        28
           6       1.00      1.00      1.00        38
           7       1.00      1.00      1.00        35
           8       1.00      1.00      1.00        33
           9       1.00      1.00      1.00        35
          10       1.00      1.00      1.00        37
          11       1.00      1.00      1.00        34
          12       1.00      1.00      1.00        34
          13       1.00      1.00      1.00        38
          14       1.00      1.00      1.00        30
          15       1.00      1.00      1.00        39
          16       1.00      1.00      1.00        17
          17       1.00      1.00      1.00        19
          18       1.00    

C:\Users\betre\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\betre\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\betre\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [247]:
# from sklearn.linear_model import LinearRegression
# from sklearn.model_selection import train_test_split
# %matplotlib inline
# from sklearn import metrics


In [248]:
# Winning_Numbers['Ball1'] =Winning_Numbers['Ball1'].astype('category')
# Winning_Numbers['Ball2'] =Winning_Numbers['Ball2'].astype('category')
# Winning_Numbers['Ball3'] =Winning_Numbers['Ball3'].astype('category')
# Winning_Numbers['Ball4'] =Winning_Numbers['Ball4'].astype('category')
# Winning_Numbers['Ball5'] =Winning_Numbers['Ball5'].astype('category')
# Winning_Numbers['Mega Ball'] =Winning_Numbers['Mega Ball'].astype('category')

# cat_feat = ['Mega Ball','Multiplier']
# for feat in cat_feat:
#     Winning_Numbers[feat] = Winning_Numbers[feat].astype('category')

In [249]:
# x = realestate[['X2 house age', 'X3 distance to the nearest MRT station', 'X4 number of convenience stores', 'X5 latitude', 'X6 longitude']]

In [250]:
# y = realestate['Y house price of unit area']


In [251]:
# Winning_Numbers1 = LinearRegression()
# Winning_Numbers1.fit(x_train, y_train)

# lm = LinearRegression()
# lm.fit(x_train, y_train)

In [252]:
# LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
#          normalize=False)

In [253]:
# X = Winning_Numbers.drop(['Mega Ball'],axis=1)
# y = Winning_Numbers['Mega Ball']

In [254]:
#from sklearn.linear_model import LogisticRegression
#from sklearn.metrics import classification_report, confusion_matrix
#models = []
#models.append(("LR",LogisticRegression(solver='liblinear')))
#print(models)

In [255]:
#import statsmodels.formula.api as smf
#model_fit3 = smf.logit(formula='MegaBall ~C(Ball1)+C(Ball2)', data=winning_numbers).fit()